examples/example4.py
This PR demonstrates the use case I am most interested in. I know it is a simple extension of your example2, but this use case would be a lot less elegant with the original `kubernetes` library. Maybe you want to add it.
=> Simultaneously watch multiple event streams without threads.

setup.py
Hi folks!
After poking around this lib in Pypi.org, I found out that "homepage" link leads to `Kubernetes python client` gh page. This PR fixes that issue.
Changes:
- supplemented module description with "asynchronous" keyword
- make url lead to right repo
Take care
Patryk
=> Fix few typos in setup.py

kubernetes_asyncio/watch/watch.py, kubernetes_asyncio/watch/watch_test.py
This PR solves two problems I encountered:
* Raise `StopIteration` for empty K8s responses (eg when the timeout expires).
* Do not process K8s error responses but pass them verbatim to the user instead.
=> Stop the iterator for empty responses and do not process ERROR responses

examples/example1.py, examples/example2.py, examples/example3.py, examples/example4.py, examples/tail.py, kubernetes_asyncio/config/__init__.py, kubernetes_asyncio/config/google_auth.py, kubernetes_asyncio/config/google_auth_test.py, kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py, kubernetes_asyncio/e2e_test/base.py, requirements.txt
* resolve #17 
* load_kube_config() is async function now (required by some autorisation provider like GKE)
* method to auto-refresh token (GKE)
=> feat: async refresh token, remove synchronous libs

kubernetes_asyncio/client/rest.py
This fixes #32 
I didn't see any relevant tests but am happy to add any test that you think should be here - unfamiliar with working in this library so I wouldn't know what makes the most sense off hand : )
=> Fix TCPConnection for verify_ssl = false

kubernetes_asyncio/watch/watch.py
resolve #29 
Not closed connections filled up a connection pool and new connections couldn't be created.
=> fix: handling timeout by watch loop

kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py
Ref: https://github.com/kubernetes-client/python-base/pull/86
=> fix: read config data with bytes (python3)

kubernetes_asyncio/config/exec_provider.py, kubernetes_asyncio/config/exec_provider_test.py, kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py
=> WIP: feat: porting exec-provider from base library

kubernetes_asyncio/config/exec_provider.py, kubernetes_asyncio/config/exec_provider_test.py
Sync with synchronous lib: https://github.com/kubernetes-client/python-base/pull/91
=> fix: pdate ExecProvider to use safe_get()

kubernetes_asyncio/config/kube_config.py, requirements.txt
This library doesn't need to use the urllib3 - it uses the iohttp instead. In this PR I remove a dependency to urllib3 from kube_config.py. The library is still required by the generated part by swagger-codegen.
I also change the required version >=1.23 due to security patches.
=> feat: remove dependency to urllib3 from kube_config, pin urlllib>=1.23 due to CVE-2018-20060

kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py, kubernetes_asyncio/e2e_test/test_extensions.py
Use safer methods to load/dump yaml.
Porting: https://github.com/kubernetes-client/python-base/pull/111
=> feat: use yaml.safe_load/dump

kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py
Add support for multiple config files.
ref: https://github.com/kubernetes-client/python-base/pull/94
=> feat: merging kubeconfig files

kubernetes_asyncio/watch/watch.py
The 'object' key may not be present in the case of unauthorized access (403) which leads to a KeyError that do not provide any information on the real error.
With this check, a sound error message with the message content is shown.
=> Check whether an object key is present on watch

kubernetes_asyncio/config/dateutil.py, kubernetes_asyncio/config/dateutil_test.py
Porting https://github.com/kubernetes-client/python-base/pull/150/ from the official client.
=> fix: parse microseconds in data-time fields

.travis.yml
Porting https://github.com/kubernetes-client/python/pull/896 from the official client.
=> chore: remove deprecated option "sudo" from Travis

requirements.txt
Signed-off-by: zane <zane@ugh.cloud>
prevents https://github.com/tomplus/kubernetes_asyncio/issues/87 until we can refactor to deal with breaking changes in aiohttp 4.0.x
=> prevent installing aiohttp 4.0 and up for now

kubernetes_asyncio/watch/watch.py, kubernetes_asyncio/watch/watch_test.py
The method Watch.Stream stores a resource version to use in the next calls if the first hasn't returned another value. 
Fixes #77
=> fix: watch.stream stores resource_version for the next call

kubernetes_asyncio/watch/watch.py, kubernetes_asyncio/watch/watch_test.py
I ported the changes from [Making watch work with read_namespaced_pod_log](https://github.com/kubernetes-client/python-base/commit/8e6f0435a38e24aac700d9ebac700bdf6138ba8c) so that watch can be used on methods with the keyword arg `watch` or the keyword arg `follow`. This should fix #97 !
=> Add compatability for follow methods

scripts/kube-init.sh
The latest version of minikube/k8s requires conntrack and e2e tests fail with the error:
`The none driver requires conntrack to be installed for kubernetes version 1.18.0`.
Ref: https://github.com/kubernetes/minikube/issues/7179
=> fix: install conntrack required by minikube

kubernetes_asyncio/config/exec_provider.py, kubernetes_asyncio/config/exec_provider_test.py
The code was (needlessly?) using shlex to split and recombine the commandline arguments which breaks compatibility with Windows systems.
The regular kubernetes client passes the `self.args` as is which appears to be safe to do. The regular client does the exact same thing.
When using `shlex` it converts something like `c:\\programdata\\chocolatey\\lib\\doctl\\tools\\doctl.exe` into `c:programdatachocolateylibdoctltoolsdoctl.exe`
Which obviously doesn't work :)
=> Removed shlex args mangling

.github/workflows/test.yaml, kubernetes_asyncio/config/__init__.py, kubernetes_asyncio/config/incluster_config_test.py, kubernetes_asyncio/config/kube_config_test.py, kubernetes_asyncio/config/openid_test.py
The latest version of isort requires start path to search files and also this version has found some unordered imports too.
=> chore: CI works with the latest isort

kubernetes_asyncio/watch/watch.py
It fixes https://github.com/tomplus/kubernetes_asyncio/issues/109.
=> fix: remove redundant close() in Watch class

kubernetes_asyncio/client/api_client.py
It solves #122 
The workaround is implemented manually on generated code. PR for OpenApi generator is on the way.
=> fix: remove checking headers if raw content is returned from rest api

scripts/kube-init.sh
Rollback temporary changes https://github.com/tomplus/kubernetes_asyncio/pull/117
=> chore: e2e tests use latest version of k8s

kubernetes_asyncio/config/kube_config.py
There is a bug to access the current context in configuration file when no configuration is loaded.
I've also added an extra warning if none of configuration files exist.
It fixes #126
=> fix: show warning if config not loaded

kubernetes_asyncio/e2e_test/test_client.py
The latest version of minikube adds a ConfigMap to the 'default' namespace, so e2e tests for deleting operation have to more precise.
=> tests: e2e tests ignore system config-maps.

kubernetes_asyncio/client/rest.py, requirements.txt
The previous default (64KiB) would cause `ValueError: Line is too long`
exceptions on watch events with large objects.
Requires aiohttp >= 3.7.0
=> Increase aiohttp read buffer to 2MiB

README.md, kubernetes_asyncio/utils/__init__.py
'Incorrect imports order/format' appeared after merging https://github.com/tomplus/kubernetes_asyncio/pull/133.
=> Fix imports order/format

kubernetes_asyncio/utils/__init__.py, kubernetes_asyncio/utils/create_from_yaml.py, kubernetes_asyncio/utils/create_from_yaml_test.py
It closes https://github.com/tomplus/kubernetes_asyncio/issues/142
=> feat: add function to create objects from dict

kubernetes_asyncio/watch/watch.py, kubernetes_asyncio/watch/watch_test.py
=> fix: Watch() raises exceptions for received errors

kubernetes_asyncio/config/__init__.py, kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py
Add new function to load kube-config from dict instead of kubeconfig:
* load_kube_config_from_dict
* new_client_from_config_dict
Add option to define temporary directory for files detached from kubeconfig (like ssl certs).
Fixes #167
=> [feat] Load kubeconfig from dict

kubernetes_asyncio/watch/watch.py, kubernetes_asyncio/watch/watch_test.py
=> fix: watch returns raw_object if detection of returned objects fail

kubernetes_asyncio/config/incluster_config.py, kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py
The latest version of OpenAPI Generator change/fix a field name to store authentication token (https://github.com/OpenAPITools/openapi-generator/pull/6469) and it causes authorization problem (#187, #188).
=> [fix] passing Bearer token in authorization header

kubernetes_asyncio/client/rest.py, scripts/rest_client_patch_read_bufsize.diff, scripts/update-client.sh
Fix https://github.com/tomplus/kubernetes_asyncio/pull/138#issuecomment-1081603551, now this change is applying as a patch for generated client.
=> [fix] add patch to update read buffer size

kubernetes_asyncio/config/incluster_config.py, kubernetes_asyncio/config/incluster_config_test.py
This PR adds an optional `client_configuration` parameter to the `InClusterConfigLoader`, aligning its behavior with the one of `KubeConfigLoader` and allowing users to manage explicit `Configuration` objects also with this loading path.
Fixes #194
=> Added optional explicit config parameter to InClusterConfigLoader

kubernetes_asyncio/stream/ws_client.py, kubernetes_asyncio/stream/ws_client_test.py
Thir PR adds a configurable heartbeat value to the WsApiClient constructor, which defaults to None. This prevents connection timeouts when executing long commands with no outputs on remote pods.
A unit test has also been added to check that the heartbeat argument is correctly received in the constructor.
Fixes #193
=> Configurable heartbeat value for WsApiClient

.github/workflows/publish.yaml
This PR provides GitHub based automation to build and publish a PyPI package when a tag is pushed. A workflow very similar to this has been successfully used without issues in the JupyterHub github organization for quite a while now.
This PR was opened following agreement about adding something like this in https://github.com/tomplus/kubernetes_asyncio/issues/201#issuecomment-1101837581.
=> ci: add workflow to publish sdist/wheel to PyPI

scripts/kube-init.sh
E2E tests have not working since K8s 1.24.0 released.
It looks like some incompatibility problems are in minikube: https://github.com/kubernetes/minikube/issues/14128
=> [chore] pin k8s version to 1.23.6 in e2e tests.

kubernetes_asyncio/config/incluster_config.py, kubernetes_asyncio/config/incluster_config_test.py
Periodically refresh ServiceAccount tokens. This is required to avoid
authentication errors when time-bound tokens [1] are rotated, and the
initially-read token expires. Time bound tokens are beta in Kubernetes
1.21, and GA in 1.22 [2].
[1]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/1205-bound-service-account-tokens
[2]: https://github.com/kubernetes/enhancements/issues/542
=> Periodically refresh ServiceAccount tokens

kubernetes_asyncio/watch/watch.py, kubernetes_asyncio/watch/watch_test.py
This PR should fix #215.
It still does not prevent the same issue from happening again. Not sure if there is a good way to prevent it.
=> fixed watch.stream bug of not working with apis with follow kwarg

kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py
=> fix: config reader handles bool types

kubernetes_asyncio/config/google_auth.py
The code was previously calling shlex.split on cmd-path in addition to cmd-args. If cmd-path had a space in it (which happens on Windows, e.g. C:\Users\<username>\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd) then shlex.split will split that command line and the command will fail.
Fixes #223
=> Don't use shlex.split on cmd-path

.github/workflows/test.yaml
Python 3.6 is not accessible in the latest Github Actions and it has reached its end-of-life.
=> [test] remove python 3.6 from tests

doc/Makefile, doc/source/conf.py, test-requirements.txt
Reverts tomplus/kubernetes_asyncio#242
This module is very slow and readthedocs.org build fails.
=> Revert "[doc] use sphinx-autoapi"

.github/workflows/test.yaml, README.md, kubernetes_asyncio/config/exec_provider_test.py, kubernetes_asyncio/config/google_auth_test.py, kubernetes_asyncio/config/kube_config_test.py, kubernetes_asyncio/config/openid_test.py, kubernetes_asyncio/e2e_test/base.py, kubernetes_asyncio/e2e_test/test_api.py, kubernetes_asyncio/e2e_test/test_batch.py, kubernetes_asyncio/e2e_test/test_client.py, kubernetes_asyncio/stream/ws_client_test.py, kubernetes_asyncio/utils/create_from_yaml_test.py, kubernetes_asyncio/watch/watch_test.py, test-requirements.txt
* replace asynctest with unittest (Python 3.8+) - it fixes https://github.com/tomplus/kubernetes_asyncio/issues/234
* replace codecov with github actions codecov/codecov-actions to upload cov reports
=> Remove deprecated packages asynctest, codecov

.github/workflows/test.yaml, scripts/kube-init.sh
1. change driver to docker (simpler to use in github actions)
2.  k8s v1.27 is not supported by mini-kube yet
=> Change K8s version from 1.23.6 to 1.26.3 in e2e tests.

kubernetes_asyncio/__init__.py, setup.py
It fix missing package issue when using pip install, and make it consistent with other packages.
=> Add dynamic package to setup.py and __init__.py

examples/tail.py, kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py
Fixes #257. This PR is based heavily on https://github.com/kubernetes-client/python-base/pull/250. It also includes the fix made [here](https://github.com/kubernetes-client/python/commit/a07531b93233a9565d973d861dc711fa26b17cc8) to the non-asyncio library. 
This change has been tested in multiple services that rely on a long running client that was previously failing due to expiring credentials.
=> [fix] support refreshing exec api credentials

kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py
This mostly imports what was done in the sync client in https://github.com/kubernetes-client/python/commit/b85aff2b3e6c950cb9128d281cd6f7394563e202
This may solve #231: if the configuration from #213 was trying to load a configuration file containing these client certificates instead of a bearer token, the log message would display and the connection to Kubernetes would fail.
=> Load certificates from plugin exec

kubernetes_asyncio/watch/watch.py, kubernetes_asyncio/watch/watch_test.py
**Issue**: receiving bookmarks in watchers is not handled and raises errors while unmarshalling. 
The official client just returns `type==BOOKMARK` together with the object. 
Even more, they have a todo to set the watcher resource_version attribute in the future; this has been done here as well. 
https://github.com/kubernetes-client/python/blob/36cfbe68a509d9b9d33395b22b6fa94d7d46c30f/kubernetes/base/watch/watch.py#L103
- Test added
- flake & isort applied
=> add bookmark support in watcher

kubernetes_asyncio/client/configuration.py, kubernetes_asyncio/client/rest.py, kubernetes_asyncio/config/kube_config.py, kubernetes_asyncio/config/kube_config_test.py, requirements.txt, scripts/rest_client_server_hostname_patch.diff, scripts/update-client.sh
This honors the `tls-server-name` parameter which can be present in a `kubeconfig` configuration file.
The implementation is similar to the one done in https://github.com/kubernetes-client/python/pull/1933
~This needs a released version of https://github.com/aio-libs/aiohttp/pull/7541~ This is implemented in [aiohttp v3.9.0](https://github.com/aio-libs/aiohttp/pull/7543).
Fix: #267
=> Support loading a custom TLS server name from `kubeconfig`

kubernetes_asyncio/config/kube_config.py
> Note: I didn't open an issue as I thought this was an obvious and trivial change.
This is because the current default will not work on windows. So it's better to delegate this to pathlib which will handle resolving the path.
=> Make the kube config path os agnostic

.github/workflows/test.yaml, setup.py
Just not see Python 3.12 support in classifiers, here I try to test it in CI and add the classifier.
=> Add Python 3.12 in CI

kubernetes_asyncio/client/rest.py, kubernetes_asyncio/e2e_test/test_apply_patch.py, scripts/rest_client_apply_patch_patch.diff, scripts/update-client.sh
=> restore rest client ablity to handle "application/apply-patch+yaml" content type

requirements.txt
=> remove setuptools from requirements

kubernetes_asyncio/dynamic/client.py
This pull request contains 3 small fixes related to timeouts, seen during a watch operation.
I don't know if they can all be applied, especially the one in rest.py since this file is generated.
=> Timeout related fixes

examples/pod_exec.py, kubernetes_asyncio/stream/ws_client.py, kubernetes_asyncio/stream/ws_client_test.py
This draft pull request provides some enhancements to the pod_exec example and ws API.
The last commit is an API break, so you may not want it.
Comments welcome, of course!
Fixes #322
=> Pod exec enhancements

kubernetes_asyncio/watch/watch.py, kubernetes_asyncio/watch/watch_test.py
Fixes https://github.com/tomplus/kubernetes_asyncio/issues/136
=> [feat] Watch() retries 410 errors

kubernetes_asyncio/config/__init__.py, kubernetes_asyncio/config/incluster_config.py, kubernetes_asyncio/config/incluster_config_test.py, kubernetes_asyncio/config/kube_config_test.py
Added load config function from https://github.com/kubernetes-client/python/blob/master/kubernetes/base/config/__init__.py#L24. It was pretty much a drop-in copy and paste, aside from having to update the `load_kube_config` call to be `await`ed. I would have copied over any tests as well, but I did not find any. Please let me know if you would like to build some up out or if you'd like me to make any other updates!
Fixes #249
=> Added `load_config` function

kubernetes_asyncio/client/rest.py, kubernetes_asyncio/client/test_rest.py
Implement timeout behavior same as official python Kubernetes client: https://github.com/kubernetes-client/python/blob/f414832bb05b946eb1758df12f08806b44dd315e/kubernetes/client/rest.py#L146
Following issues will be resolved by this fix:
- https://github.com/tomplus/kubernetes_asyncio/issues/308
- https://github.com/PrefectHQ/prefect/issues/15259
- https://github.com/PrefectHQ/prefect/issues/14954
=> fix rest api aiohttp timeout

kubernetes_asyncio/dynamic/discovery.py, kubernetes_asyncio/dynamic/discovery_test.py
Dynamic client discovery for resources with three part names, the processing fails. Allow for processing names with >2 parts.
This was failing on an OpenShift environment with the resource 'virtualmachineinstances/sev/fetchcertchain'
#342
=> allow resource names >2 parts

examples/leaderelection.py, kubernetes_asyncio/leaderelection/electionconfig.py, kubernetes_asyncio/leaderelection/leaderelection.py, kubernetes_asyncio/leaderelection/leaderelection_test.py, kubernetes_asyncio/leaderelection/leaderelectionrecord.py, kubernetes_asyncio/leaderelection/resourcelock/configmaplock.py, kubernetes_asyncio/leaderelection/resourcelock/leaselock.py
Add leaderelection module, based off of the leaderelection module in kubernetes-client/python. The module has been altered slightly to support asyncio.
Fixes #297
=> Add leaderelection module

README.md
[asyncio.run](https://docs.python.org/3/library/asyncio-runner.html#asyncio.run) is the current, documented method to begin and clean up an async event loop, as of `python3.7`.
`python3.9` is the oldest version of python that isn't EOL.
=> Update README example with `asyncio.run`

kubernetes_asyncio/client/configuration.py, kubernetes_asyncio/client/rest.py, kubernetes_asyncio/client/test_rest.py, scripts/client_configuration_disable_ssl_strict_verification_patch.diff, scripts/rest_client_disable_ssl_strict_verification_patch.diff, scripts/update-client.sh
Since Python 3.13, ssl.VERIFY_X509_STRICT is enabled by default.
Old Kubernetes clusters might have certificates that do not (yet) comply with that.
Add a (custom) configuration option to disable this flag.
Fix #349
=> patch: Add option to disable ssl.VERIFY_X509_STRICT

kubernetes_asyncio/client/api/custom_objects_api.py
Fixes #353 
After about an hour of debugging I noticed that some characters were typed incorrectly in the URL of the method `list_custom_object_for_all_namespaces_with_http_info`. I removed them and everything works fine.
=> Delete extra characters in URL

kubernetes_asyncio/client/api_client.py, kubernetes_asyncio/client/configuration.py, kubernetes_asyncio/config/incluster_config_test.py, scripts/api_client_async_refresh_api_key_hook.diff, scripts/client_configuration_async_refresh_api_key_hook.diff, scripts/update-client.sh
Rather than creating an issue, I created this draft pull request to demonstrate what the issue is.
My specific use case is I have implemented the ability to obtain AWS EKS credentials which expire every 15 minutes using an AWS async client. I suspect that more often than not, refreshing credentials will involve i/o and would benefit from async support.
=> Allow for async refresh_api_key_hook methods.

kubernetes_asyncio/dynamic/discovery.py
fix: handle ContentTypeError in dynamic client discovery
#367
When the Kubernetes API server returns a 503 Service Unavailable with text/plain 
content type instead of JSON, the dynamic client was failing with a ContentTypeError 
while trying to parse the response. This fix catches ContentTypeError in the 
get_resources_for_api_version method and handles it the same way as ServiceUnavailableError, 
allowing the client to gracefully continue with an empty resources list.
This resolves issues when accessing certain API endpoints that may temporarily 
return non-JSON responses during service unavailability
=> fix: handle ContentTypeError in dynamic client discovery
