kubernetes_asyncio/watch/watch.py
kubernetes_asyncio/watch/watch_test.py
test-requirements.txt

* support stop()
* add tests for `Watch`

feat: watch improvments

---

kubernetes_asyncio/e2e_test/base.py

feat: replace urllib3 by http.client in e2e initializer

---

kubernetes_asyncio/client/rest.py

fix: option verify-ssl impacts on server certs only

---

scripts/kube-init.sh

Porting PR https://github.com/kubernetes-client/python/pull/665

feat: e2e tests use minikube

---

CHANGELOG.md
scripts/kube-init.sh

Add information about breaking changes in v9.0.0

doc: update changelog file

---

CONTRIBUTING.md

doc: remove CLA requirement, add note about regenerating process

---

requirements.txt

Copied from: https://github.com/kubernetes-client/python/pull/897

feat: update urlib3 for CVE-2019-11324

---

README.md
examples/example4.py
kubernetes_asyncio/watch/watch.py

Watch() closes http session on exit.
Fix #103

fix: watch closes http session

---

scripts/kube-init.sh

Temporary workaround for https://github.com/kubernetes/minikube/issues/9470

chore: e2e test use k8s v1.19.2

---

scripts/kube-init.sh

Fix some bugs in the script to start minikube for e2e tests.

fix: update script to start minikube

---

kubernetes_asyncio/watch/watch.py
kubernetes_asyncio/watch/watch_test.py

Fixes https://github.com/tomplus/kubernetes_asyncio/issues/150

fix: handle 401 returned by GKE

---

kubernetes_asyncio/watch/watch.py

Fixes #152
As a plus, log streaming becomes faster.

Do not try to unmarshall log stream lines

---

kubernetes_asyncio/client/api_client.py

[fix] add missing change in latest regnerated lib

---

.github/workflows/publish.yaml

It allows to upgrade the setup-python: #208

[ci/cd] add python-version attr required by actions/setup-python@v4

---

kubernetes_asyncio/config/incluster_config.py
kubernetes_asyncio/config/incluster_config_test.py

[fix] refreshing incluster configuration

---

kubernetes_asyncio/config/kube_config.py
kubernetes_asyncio/dynamic/discovery.py

Use local logger instance to prevent reconfiguring user's logger

---

.github/workflows/test.yaml

Reverts tomplus/kubernetes_asyncio#276

Revert "chore(deps): bump codecov/codecov-action from 3 to 4"

---

README.md

add link to documentation on readthedocs.io

---

kubernetes_asyncio/watch/watch.py
kubernetes_asyncio/watch/watch_test.py

Fix stopping Watch for logs and events with timeout

---

kubernetes_asyncio/client/api_client.py
kubernetes_asyncio/e2e_test/test_apply_patch.py
scripts/api_client_strategic_merge_patch.diff

Fix content-type detection for object sending as patch

---

CHANGELOG.md

It closes https://github.com/tomplus/kubernetes_asyncio/issues/338

Add notice about a breaking change

---

setup.py

fix: add missing leaderelection package

---

setup.py

fix: add missing leaderelection.resourcelock package
